"""create pdfs table

Revision ID: a7f2b80a52ce
Revises: 30a84d438097
Create Date: 2024-09-23 18:07:48.657875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f2b80a52ce'
down_revision: Union[str, None] = '30a84d438097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pdfs_pkey')
    )
    # ### end Alembic commands ###
